spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ekp_0811
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jdbc:
    template:
      query-timeout: 3

logging:
  level:
    com:
      example:
        lizhen:
          demo:
            mapper: debug
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
